# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:51:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GlobalpageloadGetResponse(BaseModel):
    Code: Optional[str] = None
    Contents: Optional[str] = None
    Credits: Optional[str] = None
    Origin: Optional[str] = None
    PageResponseStatus: Optional[str] = None
    Seconds: Optional[str] = None
